GET http://localhost:3000
###
GET http://localhost:3000/api/customer
###
POST http://localhost:3000/api/customer HTTP/1.1
Content-Type: application/json

{
    "CustomerId": 1004,
    "FullName": "Mawin",
    "Address": "England"
}
###
PUT http://localhost:3000/api/customer/63b50cd6ba34aca8cd57983f HTTP/1.1
Content-Type: application/json

{
    "CustomerId": 1001,
    "FullName": "Bank",
    "Address": "laos"
}
###
DELETE http://localhost:3000/api/customer/63b512593a1c76a46312c302 HTTP/1.1