GET http://localhost:3000
###
GET http://localhost:3000/api/customer
###
POST http://localhost:3000/api/customer HTTP/1.1
Content-Type: application/json

{
    "CustomerId": 1005,
    "FullName": "Bass",
    "Address": "japan"
}
###
PUT http://localhost:3000/api/customer/63be3634aadb90ebbad76e4e HTTP/1.1
Content-Type: application/json

{
    "CustomerId": 1001,
    "FullName": "Bank",
    "Address": "laos"
}
###
DELETE http://localhost:3000/api/customer/63be2e10aadb90ebbad76e47 HTTP/1.1